build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ihunt/ihunt-site .
    - docker push registry.gitlab.com/ihunt/ihunt-site
