# TODO: Replace with an official image when available
image: registry.gitlab.com/citygro/docker-and-compose

variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  SERVICE: web

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose build --pull
    - docker-compose push

test:
  stage: test
  script:
    - docker-compose pull
    - docker-compose run --entrypoint 'coverage run --source . manage.py' $SERVICE test -v 2
    - docker-compose run --entrypoint 'coverage' $SERVICE report
  coverage: /\d+\%\s*$/
