# TODO: Replace with an official image when available
image: registry.gitlab.com/citygro/docker-and-compose

variables:
  DOCKER_DRIVER: overlay
  SERVICE: web
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_FILE: $SERVICE:$CI_COMMIT_REF_NAME.tar

services:
  - docker:dind

stages:
  - build
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose build --pull
    - docker save -o $IMAGE_FILE $IMAGE_TAG
  artifacts:
    name: docker-image
    paths:
      - $IMAGE_FILE

test:
  stage: test
  dependencies:
    - build
  script:
    - docker load -i $IMAGE_FILE
    - docker-compose run --entrypoint 'coverage run --source . manage.py' $SERVICE test -v 2
    - docker-compose run --entrypoint 'coverage' $SERVICE html
    - docker-compose run --entrypoint 'coverage' $SERVICE report
  artifacts:
    name: coverage
    paths:
      - .coverage
      - htmlcov/
  coverage: /\d+\%\s*$/

release:
  stage: release
  dependencies:
    - build
  script:
    - docker load -i $IMAGE_FILE
    - docker-compose push
  only:
    - tags
