version: '2.1'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:3031
    depends_on:
      - db
    environment:
      - H2_DEBUG
    image: ${IMAGE_TAG:-hunter2_app}
    ports:
      - "8080:3031"
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - static:/static
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
    tty: true

volumes:
  db: {}
  config: {}
  static: {}
  uploads_events: {}
  uploads_puzzles: {}
