version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - db:/var/lib/postgresql/data
  web:
    image: ${IMAGE_TAG:-hunter2}
    build: .
    volumes:
      - ${PWD:-.}:/usr/src/app
      - storage:/storage
      - config:/config
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db: {}
  storage: {}
  config: {}