db:
  image: postgres:9.6
  volumes:
    - ihuntsite_db:/var/lib/postgresql/data
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/usr/src/app
    - ihuntsite_storage:/storage
  ports:
    - "8000:8000"
  links:
    - db
