version: '2.1'

services:
  pipenv:
    environment:
      - http_proxy
      - https_proxy
    image: registry.gitlab.com/rconan/docker-pipenv:2018.11.29-0
    command: lock
    volumes:
      - ${PWD:-.}:/code
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:2.40.1-0
    volumes:
      - ${PWD:-.}:/files
  eslint:
    command: ["."]
    image: registry.gitlab.com/rconan/docker-eslint:5.14.1-0
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:3.7.7-0
    volumes:
      - ${PWD:-.}:/code
  webpack:
    build:
      context: .
      dockerfile: webpack/Dockerfile
      args:
        webpack_tag: 4.23.1-1
    volumes:
      - ${PWD:-.}:/usr/src/app
