version: '2.1'

services:
  app:
    depends_on:
      - db
      - redis
    environment:
      - H2_ADMINS
      - H2_DEBUG
      - H2_DOMAIN
      - H2_EMAIL_DOMAIN
      - H2_EMAIL_URL
      - H2_PIWIK_HOST
      - H2_PIWIK_SITE
      - H2_SCHEME
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
      - UWSGI_WORKERS
    image: registry.gitlab.com/hunter2.app/hunter2/app:${H2_IMAGE_VERSION:-latest}
    volumes:
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  db:
    image: postgres:9.6.11-alpine
    volumes:
      - db:/var/lib/postgresql/data
  db_exporter:
    depends_on:
      - db
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@db:5432/?sslmode=disable
    image: wrouesnel/postgres_exporter:v0.4.7
  metrics:
    image: registry.gitlab.com/hunter2.app/hunter2/metrics:${H2_IMAGE_VERSION:-latest}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - metrics:/prometheus
  redis:
    image: redis:5.0.3-alpine3.8
    volumes:
      - redis:/data
  redis_exporter:
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    image: oliver006/redis_exporter:v0.25.0
  web:
    depends_on:
      - app
    image: registry.gitlab.com/hunter2.app/hunter2/web:${H2_IMAGE_VERSION:-latest}
    ports:
      - "${H2_LISTEN:-8080}:80"
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  metrics: {}
  redis: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
