version: '2.1'

services:
  db:
    image: postgres:9.6.11-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3-alpine3.8
    volumes:
      - redis:/data
  app:
    build:
       context: .
       args:
          DEVELOPMENT: "true"
    command: runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    environment:
      - H2_DEBUG=True
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.development
      - H2_SILK
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    ports:
      - "${H2_LISTEN:-127.0.0.1:8080}:8000"
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
    tty: true

volumes:
  db: {}
  config: {}
  redis: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
