version: '2.1'

services:
  db:
    image: postgres:9.6.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
       context: .
    depends_on:
      - db
    environment:
      - H2_ADMINS
      - H2_DEBUG
      - H2_EMAIL_DOMAIN
      - H2_EMAIL_URL
      - H2_PIWIK_HOST
      - H2_PIWIK_SITE
      - H2_SCHEME
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
      - UWSGI_WORKERS
    image: ${IMAGE_TAG:-hunter2_app}
    volumes:
      - config:/config
      - static:/static
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  web:
    build: ./nginx
    image: ${IMAGE_TAG:-hunter2_web}
    ports:
      - "${H2_LISTEN:-8080}:80"
    volumes:
      - static:/static:ro
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  static: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
