version: '2.1'

services:
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - H2_DEBUG
      - H2_DOMAIN
      - H2_TEST_SEED
      - H2_SENDFILE=sendfile.backends.nginx
      - H2_SENTRY_DSN
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/app}
    volumes:
      - ${PWD:-.}:/usr/src/app
      - config:/config
      - uploads_events:/uploads/events
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
  db:
    image: postgres:9.6.11-alpine
    volumes:
      - db:/var/lib/postgresql/data
  db_exporter:
    depends_on:
      - db
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres@db:5432/?sslmode=disable
    image: wrouesnel/postgres_exporter:v0.4.7
  metrics:
    build: ./prometheus
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/metrics}
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - metrics:/prometheus
  redis:
    image: redis:5.0.3-alpine3.8
    volumes:
      - redis:/data
  redis_exporter:
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
    image: oliver006/redis_exporter:v0.25.0
  web:
    build: ./nginx
    depends_on:
      - app
    image: ${IMAGE_TAG:-registry.gitlab.com/hunter2.app/hunter2/web}
    ports:
      - 80
    volumes:
      - uploads_events:/media/events:ro
      - uploads_puzzles:/media/puzzles:ro
      - uploads_solutions:/media/solutions:ro

volumes:
  db: {}
  config: {}
  metrics: {}
  redis: {}
  uploads_events: {}
  uploads_puzzles: {}
  uploads_solutions: {}
