version: '2.1'

services:
  dot:
    command: -v -Tsvg -o/files/diagram/models.svg /files/diagram/models.dot
    image: registry.gitlab.com/rconan/docker-graphviz:0.0.1
    volumes:
      - ${PWD:-.}:/files
  jshint:
    image: registry.gitlab.com/rconan/docker-jshint:2.9.5-0
    volumes:
      - ${PWD:-.}:/code
  flake8:
    image: registry.gitlab.com/rconan/docker-flake8:3.5.0-0
    volumes:
      - ${PWD:-.}:/code
