scrape_configs:
  - job_name: hunter2_app
    dns_sd_configs:
      - names:
          - app
        type: A
        port: 8000
  - job_name: hunter2_db
    dns_sd_configs:
      - names:
          - db_exporter
        type: A
        port: 9187
  - job_name: hunter2_redis
    dns_sd_configs:
      - names:
          - redis_exporter
        type: A
        port: 9121
  - job_name: hunter2_web
    dns_sd_configs:
      - names:
          - web
        type: A
        port: 9145
